databases:
  - name: poligraph-db
    databaseName: poligraph
    user: poligraph
    plan: free

services:
  - type: web
    name: poligraph
    runtime: python
    plan: free
    buildCommand: './build.sh'
    startCommand: 'python manage.py migrate && python -m gunicorn PolygraphNew.wsgi:application --bind 0.0.0.0:$PORT'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: PolygraphNew.settings.production
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: polygraph.website,www.polygraph.website
      - key: USE_SQLITE
        value: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health/

